### ISSUE TITLE
check_fuser() function does not return proper result

### ISSUE THREAD

**Issue by pete4abw** [pete4abw/tmpwatch#1]
@erikarvstedt has reported that the return status from the check_fuser() function allows a file that is being accessed to be removed.

I tested this and indeed, there is a problem. `WIFEXISTED(status)` returns **TRUE** when child process exits normally. `WEXITSTATUS(status)` returns the exit status of the child. The `fuser()` function returns **TRUE** if the file in question is **NOT** being accessed. Counter intuitive, I know.

`$ less Trash/testfile`
in a different session
`$ tmpwatch -cmMuv 1d Trash`

testfile is removed.

Therefore,  the return value `return (WIFEXITED(ret) && WEXITSTATUS(ret) == 0);` does not evauate properly. A normal fuser test will return a TRUE for WIFEXITED and a TRUE if fuser shows no file being accessed.

@erikarvstedt proposed a patch (a while ago) to fix this.
```
-                return (WIFEXITED(ret) && WEXITSTATUS(ret) == 0);            
+                return (WIFEXITED(ret) && WEXITSTATUS(ret) != 0);
```
I will also evaluate if the macro for check_fuser (used when fuser not found) which evaluates to `0` also needs to be changed.

```
#else
#define check_fuser(FILENAME) 0
#endif
```
@mtrmac @i386x

**Comment by pete4abw** [comment]
Something like this
```
    } else {
            waitpid(pid, &ret, 0);
    }

    if (WIFEXITED(ret))                 /* child returned normally */
    {
            if (WEXITSTATUS(ret) == 0)  /* file in use of being accessed */
                    ret = 1;
            else                        /* file not in use */
                    ret = 0;
    } else
            _exit(127);                 /* abnormal exit for child */

    return ret;

}
#else
#define check_fuser(FILENAME) 0
#endif
```

**Comment by pete4abw** [comment]
The above is not entirely correct. WIFEXITED returns 0 if the file is in use. If so, WEXITSTATUS has no meaning.

FILE is open
```
$ fuser tmp/FILE
/share/extra/tmpwatch/tmp/FILE: 57410
$ echo $?
0
```

So the else statement should also return a 1 if the file is in use.

Of course, this only matters if the --fuser | -s option is used. Otherwise, there is no test.

The code should read:
```
    } else {
            waitpid(pid, &ret, 0);
    }

    if (WIFEXITED(ret))                 /* child returned normally */
    {
            if (WEXITSTATUS(ret) == 0)  /* some access error returned */
                    ret = 1;
            else                        /* file not in use */
                    ret = 0;
    } else
            ret = 1;                 /* abnormal exit for child */

    return ret;

}
#else
#define check_fuser(FILENAME) 0
#endif
```
I'm sure this can be improved upon!

**Comment by i386x** [comment]
Hello Peter, thanks for your findings! I will look at it more closer in near future.

**Comment by pete4abw** [comment]
> Hello Peter, thanks for your findings! I will look at it more closer in near future.

At your convenience. The final changes are in the commit. Remember, this only applies if the `-s | --fuser` oprion is used. Otherwise any file in use will be ignored.

```
+/* check user function returns 0 if OK, 1 if file in use */
 #ifdef FUSER
 static int
 check_fuser(const char *filename)
@@ -225,7 +226,8 @@ check_fuser(const char *filename)
     static int fuser_exists = -1;
     static char *const empty_environ[] = { NULL };
 
-    int ret;
+    int ret = 0;                       /* assume no file in use */
+    int wstatus;                       /* store return from waitpid */
     char dir[2 + PATH_MAX];
     int pid;
 
@@ -249,10 +251,20 @@ check_fuser(const char *filename)
 #endif
        _exit(127);
     } else {
-       waitpid(pid, &ret, 0);
+       waitpid(pid, &wstatus, 0);
     }
 
-    return (WIFEXITED(ret) && WEXITSTATUS(ret) == 0);
+    /* assume return is 0 */
+    /* Even if a file is in use, WIFEXITED can still return a normal termiination */
+    if (WIFEXITED(wstatus))            /* child returned normally */
+    {
+        if (! WEXITSTATUS(wstatus))    /* if some error returned */
+           ret = 1;
+    } else
+       ret = 1;                        /* abnormal exit for child */
+
+    return ret;
+
 }
 #else
 #define check_fuser(FILENAME) 0
```
